<?php

/*
 * SaintAugustin Auth Service – Filesystem Disks
 *
 * The `minio` disk uses the Flysystem S3 driver pointed at the MinIO
 * service in docker-compose.yml. Song sheets (PDF + images) live here
 * (SRS FR5). Presigned URLs are generated by the SongSheet controller.
 *
 * Ref: https://laravel.com/docs/12.x/filesystem#configuration
 * Ref: https://min.io/docs/minio/linux/developers/php/API.html
 */

return [

    'default' => env('FILESYSTEM_DISK', 'minio'),

    'disks' => [

        'local' => [
            'driver' => 'local',
            'root'   => storage_path('app/private'),
            'serve'  => true,
            'throw'  => false,
        ],

        'public' => [
            'driver'     => 'local',
            'root'       => storage_path('app/public'),
            'url'        => env('APP_URL').'/storage',
            'visibility' => 'public',
            'throw'      => false,
        ],

        // MinIO (S3-compatible). `use_path_style_endpoint` is required because
        // MinIO does not support virtual-hosted–style buckets out of the box.
        'minio' => [
            'driver'                  => 's3',
            'key'                     => env('AWS_ACCESS_KEY_ID', env('MINIO_ROOT_USER', 'minioadmin')),
            'secret'                  => env('AWS_SECRET_ACCESS_KEY', env('MINIO_ROOT_PASSWORD', 'minioadmin_changeme')),
            'region'                  => env('AWS_DEFAULT_REGION', 'us-east-1'),
            'bucket'                  => env('AWS_BUCKET', 'saintaugustin'),
            'endpoint'                => env('AWS_ENDPOINT', 'http://minio:9000'),
            'use_path_style_endpoint' => true,
            'throw'                   => true,
        ],

        // AWS S3 (optional). If you want to use a real S3 bucket instead of MinIO,
        // set the following env vars and use `FILESYSTEM_DISK=s3` in .env.
        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_ENDPOINT'),
        ],
    ],

    'links' => [
        public_path('storage') => storage_path('app/public'),
    ],

    // How long song-sheet presigned download URLs stay valid (minutes).
    // Read here (not inline in the controller) so it still resolves
    // correctly once `php artisan config:cache` snapshots this file.
    'song_sheet_url_ttl' => env('SONG_SHEET_URL_TTL', 15),

];
