<?php

/*
 * SaintAugustin Auth Service – Filesystem Disks
 *
 * The `minio` disk uses the Flysystem S3 driver pointed at the MinIO
 * service in docker-compose.yml. Song sheets (PDF + images) live here
 * (SRS FR5). Presigned URLs are generated by the SongSheet controller.
 *
 * Ref: https://laravel.com/docs/12.x/filesystem#configuration
 * Ref: https://min.io/docs/minio/linux/developers/php/API.html
 */

return [

    'default' => env('FILESYSTEM_DISK', 'local'),

    'disks' => [

        'local' => [
            'driver' => 'local',
            'root'   => storage_path('app/private'),
            'serve'  => true,
            'throw'  => false,
        ],

        'public' => [
            'driver'     => 'local',
            'root'       => storage_path('app/public'),
            'url'        => env('APP_URL').'/storage',
            'visibility' => 'public',
            'throw'      => false,
        ],

        // MinIO (S3-compatible). `use_path_style_endpoint` is required because
        // MinIO does not support virtual-hosted–style buckets out of the box.
        'minio' => [
            'driver'                  => 's3',
            'key'                     => env('MINIO_ACCESS_KEY', env('MINIO_ROOT_USER', 'minioadmin')),
            'secret'                  => env('MINIO_SECRET_KEY', env('MINIO_ROOT_PASSWORD', 'minioadmin_changeme')),
            'region'                  => env('MINIO_REGION', 'us-east-1'),
            'bucket'                  => env('MINIO_BUCKET', 'saintaugustin'),
            'endpoint'                => env('MINIO_ENDPOINT', 'http://minio:9000'),
            'use_path_style_endpoint' => true,
            'throw'                   => true,
        ],

    ],

    'links' => [
        public_path('storage') => storage_path('app/public'),
    ],

];
