#!/usr/bin/env bash
# Bring up (or update) the SaintAugustin stack on the VM.
#
# What it does:
#   1. clones / pulls the project into $INSTALL_DIR
#   2. writes a deployment .env into the project root
#   3. (re)builds the docker images with the right VITE_* baked in
#   4. brings the stack up with docker compose
#   5. waits for the services to report healthy
#
# Run as the user who owns $INSTALL_DIR (NOT as root — docker group
# membership is enough). Source config.sh first.
set -euo pipefail

: "${INSTALL_DIR:?source config.sh first}"
: "${GIT_REMOTE:?source config.sh first}"
: "${DOMAIN_APP:?source config.sh first}"
: "${DOMAIN_API:?source config.sh first}"
: "${DOMAIN_PROJECTION:?source config.sh first}"
: "${APP_KEY:?APP_KEY must be set in config.sh}"

# ── Step 1: project on disk ─────────────────────────────────────────
if [[ ! -d "$INSTALL_DIR/.git" ]]; then
  echo "[1/5] cloning ${GIT_REMOTE} → ${INSTALL_DIR}"
  git clone --branch "${GIT_BRANCH:-main}" "$GIT_REMOTE" "$INSTALL_DIR"
else
  echo "[1/5] pulling ${INSTALL_DIR} (branch ${GIT_BRANCH:-main})"
  git -C "$INSTALL_DIR" fetch --prune
  git -C "$INSTALL_DIR" checkout "${GIT_BRANCH:-main}"
  git -C "$INSTALL_DIR" pull --ff-only
fi

# ── Step 2: deployment .env ─────────────────────────────────────────
# docker-compose.yml at the repo root reads from .env; we generate a
# file with the values from config.sh on every deploy so the file
# always matches the live config.
echo "[2/5] writing ${INSTALL_DIR}/.env"
cat > "${INSTALL_DIR}/.env" <<EOF
# Generated by deployment/apache-VM/deploy.sh — do not edit by hand.

# Public URLs (used by the frontend bundle + Laravel CORS).
APP_URL=http://${DOMAIN_APP}
APP_FRONTEND_URL=http://${DOMAIN_APP}
VITE_API_BASE_URL=http://${DOMAIN_API}/api
VITE_PROJECTION_BASE_URL=http://${DOMAIN_PROJECTION}
VITE_WS_URL=http://${DOMAIN_PROJECTION}

# Loopback ports — Apache vhosts proxy here.
FRONTEND_PORT=${PORT_FRONTEND}
AUTH_SERVICE_PORT=${PORT_AUTH}
PROJECTION_SERVICE_PORT=${PORT_PROJECTION}

# Postgres
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DB_AUTH_NAME=saintaugustin_db

# Redis
REDIS_PORT=6379

# MinIO
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

# Laravel
APP_KEY=${APP_KEY}
JWT_SECRET=${JWT_SECRET}
APP_ENV=production
APP_DEBUG=false

# Mail
MAIL_MAILER=${MAIL_MAILER}
MAIL_HOST=${MAIL_HOST}
MAIL_PORT=${MAIL_PORT}
MAIL_USERNAME=${MAIL_USERNAME}
MAIL_PASSWORD=${MAIL_PASSWORD}
MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
MAIL_FROM_NAME=${MAIL_FROM_NAME}

# Image registry (used if compose pulls instead of builds)
REGISTRY=${REGISTRY}
TAG=${TAG}
EOF
chmod 600 "${INSTALL_DIR}/.env"

# Override the compose port bindings so the containers listen on
# loopback only — Apache is the sole public-facing entry. Without
# this, the upstream ports would be world-reachable.
cat > "${INSTALL_DIR}/docker-compose.override.yml" <<EOF
# Generated by deployment/apache-VM/deploy.sh — do not edit by hand.
services:
  auth-service:
    ports: !override
      - "127.0.0.1:${PORT_AUTH}:8000"
  projection-service:
    ports: !override
      - "127.0.0.1:${PORT_PROJECTION}:3000"
  frontend:
    ports: !override
      - "127.0.0.1:${PORT_FRONTEND}:80"
EOF

# ── Step 3 & 4: build + up ──────────────────────────────────────────
cd "$INSTALL_DIR"
echo "[3/5] docker compose build"
docker compose build \
  --build-arg "VITE_API_BASE_URL=http://${DOMAIN_API}/api" \
  --build-arg "VITE_PROJECTION_BASE_URL=http://${DOMAIN_PROJECTION}" \
  --build-arg "VITE_WS_URL=http://${DOMAIN_PROJECTION}"

echo "[4/5] docker compose up -d"
docker compose up -d

# ── Step 5: wait for health ─────────────────────────────────────────
echo "[5/5] waiting for services to come up…"
for i in $(seq 1 30); do
  ok=true
  for url in \
    "http://127.0.0.1:${PORT_FRONTEND}/" \
    "http://127.0.0.1:${PORT_AUTH}/health" \
    "http://127.0.0.1:${PORT_PROJECTION}/health"; do
    if ! curl -fsS --max-time 2 "$url" >/dev/null 2>&1; then
      ok=false; break
    fi
  done
  if $ok; then
    echo "all services healthy."
    break
  fi
  sleep 2
done

cat <<EOF

Deploy complete:
  http://${DOMAIN_APP}/
  http://${DOMAIN_API}/api/health
  http://${DOMAIN_PROJECTION}/health

Tail logs:        cd ${INSTALL_DIR} && docker compose logs -f
Tear down:        ./teardown.sh
EOF
